apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "1"
data:
  APP_ENV: {{ .Values.environment | quote }}
  LOG_LEVEL: "INFO"
  QUEUE_BACKEND: {{ .Values.queue.backend | quote }}
  STORAGE_QUEUE_ACCOUNT_URL: {{ .Values.queue.accountUrl | quote }}
  STORAGE_QUEUE_NAME: {{ .Values.queue.name | quote }}
