apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keyvault-secrets-provider
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "1"
spec:
  provider: azure
  secretObjects:
    - secretName: db-connection-secret
      type: Opaque
      data:
        - key: DATABASE_URL
          objectName: DATABASE-URL
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true" # Uses the AKS Secrets Provider User-Assigned Managed Identity, authorized in IaC
    userAssignedIdentityID: ""   # Leave empty to use default VM-assigned identity
    keyvaultName: {{ .Values.keyvault.name | quote }}
    tenantId: {{ .Values.keyvault.tenantId | quote }}
    objects:  |
      array:
        - |
          objectName: DATABASE-URL
          objectType: secret
          objectVersion: ""
