apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-worker
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: worker
spec:
  {{- if not .Values.worker.autoscaling.enabled }}
  replicas: {{ .Values.worker.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/component: worker
    spec:
      serviceAccountName: notification-worker
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.worker.terminationGracePeriodSeconds }}
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "-m", "app.worker"]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          envFrom:
            - configMapRef:
                name: notification-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-connection-secret
                  key: DATABASE_URL
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                # Checks if the heartbeat file was updated in the last 1 minute (60 seconds)
                - "find /tmp/worker-heartbeat -mmin -1 | grep ."
            initialDelaySeconds: 15
            periodSeconds: 15
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets"
              readOnly: true
            - name: tmp-volume
              mountPath: /tmp
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "keyvault-secrets-provider"
        - name: tmp-volume
          emptyDir: {}
